### ISSUE TITLE
Validate that both seqtable_readyforanalysis and taxa_wsp_readyforanalysis contain 1454 ASVs

### ISSUE THREAD

**Issue by befriendabacterium** [apascualgarcia/ReplayEcology#1]

**Comment by apascualgarcia** [comment]
Reg. your comment in the pull request thread:

> Conflict in taxa_wsp_readyforanalysis.csv is because it should have 1454 ASVs, instead of 1480 ASVs, I think. I assume your downstream analysis works with the 1480 version because it uses the ASV names rather than order, so doesn't matter if there are some redundant ASVs in taxa table. But if possible to use 1454 ASV version would recommend for tidyness.

I run again the scripts after merging and, as far as I can see, the number of ASVs is 1454 but the last ASV name is 1480, because naming was performed before filtering. As soon as both table and taxa are matched (and they are) we are done I think
