### ISSUE TITLE
Documentation for Statistical Analysis part of the pipeline

### ISSUE THREAD

**Issue by befriendabacterium** [apascualgarcia/ReplayEcology#2]

**Comment by apascualgarcia** [comment]
What statistical analysis are you exactly referring to?

**Comment by befriendabacterium** [comment]
Basically anything downstream of my code/the main analyses described in the Results section of the paper. I've left a little heading for you to continue the documentation at the end. I distinguish my 'Bioinformatic' from your 'Statistical' analysis, but feel free to call it what you want.
